# helm/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-todo
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: dotnet-todo
  template:
    metadata:
      labels:
        app: dotnet-todo
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:{{ .Values.service.targetPort }}"
          livenessProbe:
            httpGet:
              path: /todoitems
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /todoitems
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5