apiVersion: v1
kind: Service
metadata:
  name: dotnet-todo
spec:
  type: {{ .Values.service.type | default "NodePort" }}
  selector:
    app: dotnet-todo
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      {{- if eq (.Values.service.type | default "NodePort") "NodePort" }}
      nodePort: 30001
      {{- end }}